name: 'Setup Git Test Environment'
description: 'Sets up a Git test environment for running tests'

runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Verify Git installation
      shell: bash
      run: |
        git --version
        echo "Git is properly configured for tests"